In [1]:
import pandas as pd

In [ ]:
main = pd.read_csv('Netea_impaired_combat_corrected_data.csv').T
main = pd.read_csv('Khatri_combat_corrected_data.csv').T

# main = pd.read_csv('Netea_balanced_combat_corrected_data.csv').T





# main=pd.read_csv('main.csv')
main = main.rename(columns=main.iloc[0]).drop(main.index[0])

meta = pd.read_csv('meta.csv',index_col=0)

In [5]:
main

,0,1,2,3,4,5,6,7,8,9,...,84,85,86,87,88,89,90,91,92,93
Gene,ANXA3,AQP9,ARG1,ASAH1,ATG3,AZU1,BCAT1,BCL2L11,BCL6,BMPR2,...,TLE4,TLR1,TP53BP1,TRIB2,TXN,TYK2,VAMP5,VRK2,ZAP70,ZDHHC17
CAP0001,9.055207,12.438607,8.846473,6.282786,8.295644,3.72185,5.91559,4.117899,8.904199,4.923181,...,7.509093,6.669138,4.646637,5.528588,10.965597,9.023715,7.944422,4.425433,5.41445,5.961875
CAP0002,8.766083,13.558442,7.228186,6.154129,7.89088,7.794493,5.960057,4.663706,9.714444,3.940265,...,6.385369,6.248246,5.334697,6.822346,10.947226,10.0936,7.248075,4.45186,5.496178,6.921528
CAP0003,8.847718,12.648039,8.033062,6.864345,8.070978,5.127357,5.602061,3.776186,9.201898,5.376884,...,6.916736,7.011698,4.089938,5.624028,10.354701,9.810595,8.490455,4.815896,6.00454,6.203368
CAP0004,6.713844,11.658323,6.770926,6.13857,7.796897,4.509221,4.335685,4.500346,8.074819,4.963399,...,6.475021,6.40031,5.069355,6.488158,10.245123,9.396378,7.519975,3.796694,6.266399,5.821224
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GSM2500463,10.24057,12.573966,11.481726,7.672685,8.062832,11.055158,6.814492,5.077687,9.475951,5.176972,...,7.728983,7.763472,4.151194,4.054738,11.136659,9.79887,8.416697,4.555249,4.128073,7.055513
GSM2500465,7.789477,9.423124,7.735413,5.813358,5.738126,5.649661,3.977479,3.681902,8.574544,5.392407,...,6.196111,5.216246,5.754477,6.397055,8.998544,8.676639,8.710052,4.066588,6.109788,4.55545
GSM2500467,10.570457,11.947052,7.74385,5.828006,8.908986,5.46765,3.618616,3.683093,9.102825,5.060591,...,7.526851,8.310047,3.957484,4.40681,11.86458,9.551626,11.406863,5.977171,4.376655,7.240206
GSM2500469,10.702046,12.398138,8.275495,7.087204,9.221173,6.328502,5.839475,5.011949,8.955629,4.221252,...,7.60027,8.023555,4.210622,5.805192,11.386012,9.052879,9.210231,5.240379,4.095794,7.074672
GSM2500471,9.711922,12.344687,10.472172,6.873817,8.373443,10.428801,6.083988,4.539494,8.41723,5.159236,...,7.343743,6.332756,5.987262,5.46103,11.872552,9.515441,7.769159,4.29479,5.055904,7.617514

In [20]:
main.shape

(1274, 194)

In [21]:
main.head()

,ABCE1,AEBP2,ALG8,ATR,BCAS2,BTBD1,BTF3L4,BUB3,BZW2,C1QBP,...,ZFP1,ZHX1,ZMYM4,ZNF14,ZNF227,ZNF432,ZNF559,ZNF567,ZNF75A,ZZZ3
CAP0001,5.770311,4.58961,5.652066,3.353692,4.284542,5.775141,6.736516,5.665864,6.787793,7.921607,...,4.000293,4.18044,5.688253,6.492971,5.059673,4.155566,5.319324,3.188752,5.539237,5.376234
CAP0002,5.533009,4.287022,5.273277,3.790109,4.702455,5.760993,5.186812,5.436241,6.230216,7.538863,...,3.780165,4.292046,4.38135,7.843215,4.518375,3.471271,4.040525,2.591724,5.180422,4.868028
CAP0003,5.695098,5.181174,5.882368,3.616235,4.164561,5.592875,5.937123,5.918471,6.309521,7.661305,...,2.117659,3.882586,5.544296,6.85042,4.895723,4.68541,5.318127,4.562189,5.528094,5.217875
CAP0004,6.198338,5.296979,6.007996,3.847902,5.057245,5.960527,6.407928,6.374387,6.777255,7.987149,...,3.591091,4.924397,5.948193,7.185452,5.226771,3.840383,5.871458,4.114712,4.457478,5.559887
CAP0005,4.393348,5.133299,5.112961,2.570163,5.432136,5.673157,6.683321,4.896105,6.05443,7.064439,...,3.287139,3.775436,4.909883,6.948592,4.233512,4.323946,5.239863,3.363389,5.0194,4.329254

In [15]:
meta.shape

(1290, 3)

In [16]:
meta.head()

             Age  Gender  Mortality
Sample_Name
CAP0001       70       0          1
CAP0002       64       0          0
CAP0003       47       0          0
CAP0004       71       1          0
CAP0005       45       0          0

In [22]:
data= pd.merge(main,meta,left_index=True, right_index=True, how='left')
data.to_csv('Netea_balanced_combat_corrected_data_with_meta.csv', index=False)

In [23]:
data=pd.read_csv("Netea_balanced_combat_corrected_data_with_meta.csv")
data.shape

(1274, 197)